config/routes.rb
Newsletter::Engine.routes.draw do

  resources :newsletters, except: [:show,:index] do
    member do 
      get :unpublish
      get :publish
      get :editor
    end
    collection do
      get :sort
    end
    resources :pieces, :only => [:new]
  end
  resources :pieces, :only => [:edit,:create,:update,:destroy]
  resources :designs do
    resources :elements, :only => [:index,:new,:create]
  end
  resources :elements, :only => [:edit,:create,:update,:destroy]

  # get "/:newsletter_id/areas/:id/sort" => "areas#sort", to: 'sort_area'
  get '/:newsletter_id/areas/:id/sort', to: 'areas#sort', as: 'sort_area'

  get '/newsletters/:id/:mode' => 'newsletters#show', to: :public_newsletter_mode
  get '/newsletters/:id/public' => 'newsletters#show', to: :public_newsletter
  get '/newsletters/:id' => 'newsletters#show', to: :newsletter
  get '/newsletters' => 'newsletters#index', to: :newsletters
  root :to => 'newsletters#index'
end

#public top-level routes
Rails.application.routes.draw do
  get '/newsletters/archive' => 'newsletter/newsletters#archive', to: :newsletter_archive
  get '/newsletters/:id/:mode' => 'newsletter/newsletters#show', to: :public_newsletter_mode
  get '/newsletters/:id/public' => 'newsletter/newsletters#show', to: :public_newsletter
end

app/models/newsletter/application_record.rb
module Newsletter
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
    table_name_prefix= "newsletter_"
  end
end

app/models/newsletter/area.rb
require "deleteable"

module Newsletter
  class Area < ApplicationRecord
    belongs_to :design, :class_name => 'Newsletter::Design'
    belongs_to :updated_by, :class_name => 'User'
    # FIX_ME this should be has_many through:
    has_many :area_elements
    has_many :elements, -> { order("name")},
              through: :area_elements, 
              :class_name => 'Newsletter::Element'
    # the above should update the commented out below (pre-rails-4)
    # has_and_belongs_to_many :elements, :order => 'name', :join_table => 
    #   "#{::Newsletter.table_prefix}areas_#{::Newsletter.table_prefix}elements",
    #   :class_name => 'Newsletter::Element'
    has_many :pieces, -> { order("sequence")}, class_name: 'Newsletter::Piece'

  
    # FIX_ME uncomment attr_accessor :_destroy
    # attr_accessor :_destroy

    # FIX_ME uncomment attr_protected :id
    # attr_protected :id
  
    validates_presence_of :name
    #FIXME: make this work with deletable or convert to auditable, and extend it to access destroyed records
    #validates_uniqueness_of :name, :scope => :design_id
  
    # FIX_ME uncomment scopes
    # scope :active, :conditions => {:deleted_at => nil}
    # scope :by_name, lambda {|name| {:conditions => {:name => name}}}

    # FIX_ME uncomment Deleteable
    # include Deleteable
  
    # returns field data so that Newsletter::Design.export(instance) can export itself to a YAML file
    def export_fields
      { :name => name,
        :description => description 
      }
    end

    # builds areas from data pulled out of an exported YAML file by Newsletter::Design.import(class)
    def self.import(design,data,updater)
      area = self.create!(name: data[:name], 
                        description: data[:description],
                        design: design,
                        updated_by: updater)
    end
  end
end

app/models/newsletter/area_element.rb
# joins two models with has_many through
module Newsletter
  class AreaElement < ApplicationRecord
    belongs_to :area, :class_name => 'Newsletter::Area'
    belongs_to :element, :class_name => 'Newsletter::Element'
  end
end

app/models/newsletter/asset.rb
module Newsletter
  class Asset < ApplicationRecord
    belongs_to :newsletter_field
    belongs_to :newsletter_piece
  end
end

app/models/newsletter/field.rb
=begin rdoc
Author::    Chris Hauboldt (mailto:biz@lnstar.com)
Copyright:: 2009 Lone Star Internet Inc.

Defines the data behaviour of a Newsletter::Piece's fields. Tied to Newsletter::Pieces through Newsletter::Elements.

This is a base object and is never directly used, but is used to define different fields through Single Table Inheritance.

=end
require "deleteable"

module Newsletter
    class Field < ApplicationRecord
      # ##
      self.table_name =  "newsletter_fields"
      belongs_to :element, :class_name => 'Newsletter::Element'
      has_many :field_values, :class_name => 'Newsletter::FieldValue'
      belongs_to :updated_by, :class_name => 'User'

      # FIX_ME: Rails 3
      # attr_accessor :_destroy

      acts_as_list :scope => :element, :column => :sequence

      validates_presence_of :name

      #### 
=begin
      FIXME: make this work with deletable or convert to auditable, and extend it to access destroyed records
      validates_uniqueness_of :name, :scope => [:element_id], :unless => Proc.new { |field|
        field.new_record? ? Field.find(:first,:conditions =>
        ["name=? and element_id=? and deleted_at is null", field.element_id]).nil? :
        Field.find(:first,:conditions =>
        ["name=? and element_id=? and id!=? and deleted_at is null", field.element_id,
        field.id]).nil? }
=end
      
      # FIX_ME uncomment deleteable
      # include Deleteable

      # returns field data so that Newsletter::Design.export(instance) can export itself to a YAML file  
      def export_fields
        { 
          :name => name,
          :label => label,
          :sequence => sequence,
          :is_required => is_required,
          :description => description,
          :type => self[:type],
        }
      end

      # returns field data so that Newsletter::Design.export(instance) can export itself to a YAML file
      def self.import(element,data, updater)
        return unless data[:type]
        field = data[:type].constantize.new(
          :name => data[:name],
          :label => data[:label],
          :sequence => data[:sequence],
          :is_required => data[:is_required],
          :description => data[:description]
        )
        field.element = element
        field.updated_by = updater
        field.save
      end

      # returns a pieces value for a given Newsletter::Field
      def value_for_piece(piece,safe=true)
        return get_value(piece).to_s.html_safe if safe
        get_value(piece).to_s
      end

      # sets a pieces value for a Newsletter::Field
      def set_value_for_piece(piece,params)
        params.each_pair do |key,value|
          set_value(piece,key,value)
        end
      end

      def set_value(piece,key,value)
        field_value = field_values.by_piece(piece).by_key(key).first
        if field_value
          field_value.update_attribute(:value,value)
        else
          field_value = piece.field_values.build(:key => key,:value => value)
          field_value.field_id = self.id 
        end
      end

      def get_value(piece,key=nil)
        return field_values.by_piece(piece).by_key(key).first.try(:value) if key  
        field_values.by_piece(piece).first.try(:value)
      end

      # morph into a different Newsletter::Field type(if a user changes the type of a field)
      def self.morph(field,type)
        return field if field.class.name.eql?(type.to_s)
        return type.constantize.new(field.attributes) if field.new_record?
        field.update_attribute('type',type)
        Field.find(field.id)
      end

      # find the partial to display a form for creating a Newsletter::Piece
      def form_partial_path
         "newsletter/fields/#{type.to_s.gsub(/.*Newsletter::Field::/,'').gsub(/([^A-Z])([A-Z])/,'\\1_\\2').downcase}"
      end

      # helper for selecting type of field to use when creating/editing a Newsletter::Field.
      def self.valid_types
        @valid_types = ['Newsletter::Field::Text','Newsletter::Field::TextArea','Newsletter::Field::InlineAsset']
      end
    end
end

app/models/newsletter/field/text.rb
=begin rdoc
Author::    Chris Hauboldt (mailto:biz@lnstar.com)
Copyright:: 2009 Lone Star Internet Inc.

Dumb text field, created so that we can choose for them to have text areas and text fields.

=end

module Newsletter
    class Field::Text < Field
      def keys
        ['text']
      end
    end
end

app/controllers/newsletter/application_controller.rb
require 'cancancan'
module Newsletter
  class ApplicationController < ActionController::Base
    # layout Newsletter.layout
    # render layout: false

    load_and_authorize_resource

    helper :'newsletter/layout'
  end
end

app/controllers/newsletter/areas_controller.rb
module Newsletter 
  class AreasController < ApplicationController
    
    before_action :find_area, :except => [:create, :new, :index]
    before_action :find_design, :except => [:destroy,:sort]
  
    def sort
      @newsletter = Newsletter.find(params[:newsletter_id])
      @area.pieces.active.by_newsletter(@newsletter).each do | piece |
        piece.update_attribute(:sequence, params["piece"].index(piece.id.to_s).to_i+1)
      end
      head :ok
    end
  
    protected
  
    def find_design
      @design = Design.find(params[:design_id])
    end
    
    def find_area
      @area = Area.find(params[:id])
    end
  end
end

app/controllers/newsletter/designs_controller.rb
# FIX_ME uncomment deleteable
require "deleteable"

module Newsletter
  class DesignsController < ApplicationController
    before_action :find_design, :except => [:new, :create, :index]

    # FIX_ME uncomment deleteable
    # include DeleteableActions

    def index
      @designs = Design.order(:name).paginate(page: (params[:page] || 1), 
        per_page: (params[:per_page] || 30))
    end

    def show
      @areas = @design.areas.active
    end

    def new
      @design = Design.new
    end

    def edit
    end

    # POST /designs
    def create
      @design = Design.new(design_params)
      @design.updated_by = current_user

      if @design.save
        redirect_to edit_design_path(@design), notice: "Design was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /designs/1
    def update
      if @design.update(design_params)
        redirect_to edit_design_path(@design), notice: "Design was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @design.delete
      redirect_to(designs_url)
    end
    
    protected
    
    def find_design
      @design = Design.find(params[:id])
    end

    def design_params
      params.require(:design).permit(:name,:description, :stylesheet_text, :html_text, newsletters_attributes: [:design_id, :name, :description])
    end

  end
end

app/controllers/newsletter/elements_controller.rb
module Newsletter
  class ElementsController < ::Newsletter::ApplicationController
    before_action :authenticate_user!
    before_action :find_element, :except => [:new,:create,:index]
    before_action :find_design
    before_action :find_fields, :except => [:new,:create,:index]
    before_action :find_field_types, :only => [:new,:create,:edit,:update]
    
    # include DeleteableActions  

    def index
      @elements = @design.elements#.by_design(@design).paginate(:page => params[:page])
    end

    def new
      @element = @design.elements.build
      @fields = [Field.new]
    end

    def edit
    end

    def create
      @element            = @design.elements.build(element_params)
      @element.updated_by = current_user

      respond_to do |format|
        if @element.save  
          format.html { redirect_to design_elements_path(@design), notice: 'Design element was successfully created.' }
          # format.json { render :show, status: :created, location: @element }
        else
          format.html { render :new, status: :unprocessable_entity }
          # format.json { render json: @element.errors, status: :unprocessable_entity }
        end
      end      
    end
    
    def update
      respond_to do |format|
        if @element.update_attributes(params[:element])
          flash[:notice] = 'Element was successfully updated.'
          format.html { redirect_to(design_elements_path(@design)) }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
        end
      end
    end

    def destroy
      @element.destroy
      redirect_to(design_elements_path(@design))
    end
  
    protected
    def find_element
      @element ||= Element.find_by(id: params[:id])
    end
  
    def find_design
      return @design ||= @element.design if @element && @element.design.present?
      @design ||= Design.find_by(id: params[:design_id])
    end
  
    def find_fields
      return @fields ||= @element.fields if @element && @element.fields.present?
      @fields ||= [Field.new]
    end
  
    def find_field_types
      @field_types ||= Field.valid_types
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name, :description, :html_design, :deleted_at, :design_id)
    end

  end
end

app/controllers/newsletter/fields_controller.rb
module Newsletter
  class FieldsController < ApplicationController
  end
end

app/controllers/newsletter/newsletters_controller.rb
module Newsletter
  class NewslettersController < ApplicationController
    # before_action :_set_current_user
    # FIX_ME: before_action :authenticate! should be here instead
    before_action :authenticate_user!
    before_action :set_newsletter, only: %i[ show edit update destroy ]

    helper_method :newsletter
    def sort
      Newsletter.all.each do | newsletter |
        newsletter.sequence = params["newsletters"].index(newsletter.id.to_s)+1
        newsletter.save
      end
      head :ok
    end
  
    def archive
      @newsletters = Newsletter.published
      render :layout => ::Newsletter.archive_layout
    end

    def stylesheet

    end
  
    def publish
      if @newsletter.publish
        flash[:notice] = 'Newsletter Published'
      else
        flash[:notice] = @newsletter.errors
      end
      redirect_to(newsletters_path)
    end
  
    def unpublish
      if @newsletter.unpublish
        flash[:notice] = 'Newsletter UnPublished'
      else
        flash[:notice] = @newsletter.errors
      end 
      redirect_to(newsletters_path)
    end
  
    def index
      @newsletters = ::Newsletter::Newsletter.active#.order('created_at desc, published_at desc').paginate(:page => params[:page])
    end
  
    def show
      return redirect_to(main_app.newsletter_archive_path) unless @newsletter.present?
      respond_to do |format|
        format.html { render layout: false }
        format.css  { render layout: false, content_type: 'text/css' }
      end
    end

    def editor
      params[:editor] = '1'
      render :show, layout: false
    end

    def new
      @newsleter  = Newsletter.new
      @designs    = Design.active
    end

    def edit
      @designs = Design.active
    end

    def create
      @newsletter = Newsletter.new(newsletter_params)
      best_user =User.last
      @newsletter.updated_by    = best_user

      if @newsletter.save
        redirect_to @newsletter, notice: "Newsletter was successfully created."
      else
        render :new, status: :unprocessable_entity
      end

    end

    def update
      if @newsletter.update_attributes(params[:newsletter])
        flash[:notice] = 'Newsletter was successfully updated.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        @designs = Design.active
        render :action => "edit"
      end
    end

    def destroy
      @newsletter.destroy
      redirect_to(newsletters_url)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_newsletter
        @newsletter = Newsletter.find(params[:id])
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      # strong_params = params.require(:newsletter).permit(:name, :description)
      # strong_params
      params.require(:newsletter).permit(:name, :description, :design_id)
    end
    
  end
end

app/controllers/newsletter/pieces_controller.rb
module Newsletter
  class PiecesController < ApplicationController
    before_action :find_newsletter
    before_action :find_element
    before_action :find_area

    def new
      @piece = Piece.new({
        :area_id => @area.id,
        :element_id => @element.id,
        :newsletter_id => @newsletter.id
      })
    end

    def edit
    end

    def create
      @piece = Piece.new(params[:piece])
      if @piece.save
        flash[:notice] = 'Piece was successfully created.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        render :action => "new"
      end
    end

    def update
      if @piece.update_attributes(params[:piece])
        flash[:notice] = 'Piece was successfully updated.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        render :action => "edit"
      end
    end

    def destroy
      @piece.destroy
      redirect_to(edit_newsletter_path(@newsletter))
    end
  
    protected 
  
    def find_newsletter
      @newsletter ||= (@piece.try(:newsletter) || 
        ::Newsletter::Newsletter.find(params[:newsletter_id] || 
        params[:piece][:newsletter_id]))
    end
  
    def find_element
      @element ||= (@piece.try(:element) || 
        Element.find(params[:element_id] || params[:piece][:element_id]))
    end
  
    def find_area
      @area ||= (@piece.try(:area) || 
        Area.find(params[:area_id] || params[:piece][:area_id]))
    end
  end
end

app/views/newsletter/newsletters/_form.html.erb
<%= form_with(model: newsletter) do |form| %>
  <% if newsletter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
        <% newsletter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if newsletter.design.nil? %>

    <div>
      <%= form.label :design, style: "display: block" %>
      <%= form.select :design_id, @designs.collect {|design| [ design.name, design.id ] } %><br />


    </div>
    <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newsletter/newsletters/_head.html.erb
<% unless is_email? %>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/le-frog/jquery-ui.css">
<%= javascript_include_tag 'newsletter/application' %>
<%= csrf_meta_tag %>
<%= yield :head_content %>
<style>
.edit_link {
   font-family: Verdana, Arial, Helvetica, sans-serif;
   font-size: 10pt;
   font-weight: bold;
}

a.edit_link {
   color: #6fc143;
   text-decoration: none;
}

a.edit_link:hover {
   color: #469a18;
}

.delete_link {
   font-family: Verdana, Arial, Helvetica, sans-serif;
   font-size: 10pt;
   font-weight: bold;
}

a.delete_link {
   color: #d25151;
   text-decoration: none;
}

a.delete_link:hover {
   color: #a21010;
}

.piece_tool {
   background: #f8f9b0;
   width: 100px;
   padding: 5px;
   border-top: 1px dashed black;
   border-left: 1px dashed black;
   border-right: 1px dashed black;
}

</style>
<% end %>

app/views/newsletter/newsletters/_newsletter.html.erb
<% unless is_email? %>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title><%= @newsletter.name %></title>
  <link rel="stylesheet" type="text/css" media="screen" href="<%= "/newsletters/#{@newsletter.id}/stylesheet.css" %>"/>
  <%= render 'newsletter/newsletters/head' %>
</head>
<body>
<% else %>
<!DOCTYPE html>
<style>
  <%= @newsletter.design.stylesheet_text %>
</style>
<% end %>
  <%= render :inline => File.readlines(@newsletter.design.view_path).join, :locals => @newsletter.locals %>
<% unless is_email? %>
</body>
</html>
<% end %>

app/views/newsletter/newsletters/_newsletter_area.html.erb
<% unless params[:editor] %>
  <% area.pieces.by_newsletter(@newsletter).each do |piece| %>
      <% begin %>
        <%= render :inline => piece.element.html_text, :locals => piece.locals %>
      <% rescue => e %>
        <!-- Error rendering piece: <%=  piece.element.html_text %>/ <%= piece.id %> with data <%=h piece.locals.inspect %>  and template: <%=h piece.element.html_text %> <br/> <%= e.message %><br/> <%= e.backtrace.join(",") %> -->
      <% end %>
  <% end %>
<% else %>
  <%= div_for area do %>
    <% area.pieces.by_newsletter(@newsletter).each do |piece| %>
      <%= div_for piece, {:onMouseOver => "\$('modify_piece_#{piece.id}').show()",
                :onMouseOut => "\$('modify_piece_#{piece.id}').hide()", :class => 'sortable' } do %>
        <!--Element Template - <%= piece.element.view_path %> -->
        <%= content_tag :div, link_to("Delete", piece, :confirm => 'Are you sure?', 
                    :method => :delete, :class=> "delete_link") + 
                    " | " + 
                    link_to("Edit", edit_piece_path(piece), :target => '_top', :class => "edit_link"),
                    :id=>"modify_piece_#{piece.id}", :style => "display:none", :class => "piece_tool" %>
        <% begin %>
        <%= render :inline => piece.element.html_text, :locals => piece.locals %>
        <% rescue => e %>
        Error rendering piece: <%=  piece.element.html_text %>/ <%= piece.id %> with data <%=h piece.locals.inspect %>  and template: <%=h piece.element.html_text %> <br/> <%= e.message %><br/> <%= e.backtrace.join(",") %>
        <% end %>
      <% end %>
    <% end %>
  <!--  = sortable_element("area_#{area.id}", :tag=>:div, 
      :constraint =>  :vertical, :url => sort_area_path(:id=>area.id,:newsletter_id=>@newsletter.id)) %> -->
  <% end %>
<% end %>

app/views/newsletter/newsletters/archive.html.erb
<%= title "Newsletter Archive" %>

<ul style="margin-bottom: 100px;">
<% @newsletters.published.each do |newsletter| %>
	<li><%= link_to newsletter.name, newsletter.public_url('public') %></li>
<% end %>
</ul>

app/views/newsletter/newsletters/edit.html.erb
<%= title "Edit Newsletter" %>
<label>Design</label>
<div style="font-size: 11pt; padding-top: 5px;"><%= @newsletter.design.name %> </div><br />
<%= render "form", newsletter: @newsletter %>

<% if @newsletter.design %>
 <% @newsletter.areas.each do |area| %>
   <%= form_tag new_newsletter_piece_path(@newsletter), :method => :get, :id => "add_element_for_area_#{area.id}" do %>
      <%= hidden_field_tag 'area_id', area.id %>
      <%= label_tag "area_#{area.id}_element_id", "Area: #{area.name.humanize}" %>
      <%= select_tag 'element_id',  options_from_collection_for_select(area.elements, 'id', 'name'), :style=>'margin-right: 10px;', :id => "area_#{area.id}_element_id" %>
      <%= submit_tag 'Add Element', :class => 'button', :id => "add_element_#{area.id}" %>
      <div style="clear: left;"></div>
   <% end %>
<% end %>

<p><b>Newsletter Window Size: </b>
<%# [[320,568],[640,480],[800,600],[1024,768],[1280,1024],[1600,1200]].each do |width,height| %>
	<%#= link_to_function "#{width}x#{height}","$('#preview').css({height: '#{height}px', width: '#{width}px'})" %>
<%# end %>
</p>
<%= content_tag :iframe, @newsletter.name, :id => 'preview', :src => editor_newsletter_path(@newsletter), :width => 800, :height => 600 %>


<% end %>

<%= content_for :page_navigation do %>
  <div>
    <%= link_to "Back", newsletters_path, :class => 'button' %>
  </div>
<% end %>

app/views/newsletter/newsletters/index.html.erb
<%= title "Newsletters" %>
<div>
  <%= link_to "New Newsletter", new_newsletter_path, :class => 'button' %>
  <%# FIX_ME uncomment will_paginate %>
<div><br /><br /><%#= will_paginate @newsletters %></div>
<table class="list" cellpadding="1" cellspacing="0">
  <tr class="title">
    <td>Name</td>
    <td colspan="3"> </td>
  </tr>
  <% for newsletter in @newsletters %>
    <tr class="<%= cycle('odd','even') %>">
      <td><%=h newsletter.name %></td>
	    <% if newsletter.published? %>
	    <td><%= link_to 'Un&ndash;Publish'.html_safe, unpublish_newsletter_path(newsletter), :class=>"button" %></td>
	    <% else %><td><%= link_to 'Publish', publish_newsletter_path(newsletter), :class=>"button" %></td>
	    <% end %>
      <td><%= link_to "Edit", edit_newsletter_path(newsletter), :class => 'button' %></td>
      <td><%= link_to "Delete", newsletter, :confirm => 'Are you sure?', :method => :delete, :class => 'button' %></td>
    </tr>
  <% end %>
</table>


<%= content_for :page_navigation do %>
<div>
  <%= link_to "New Newsletter", new_newsletter_path, :class => 'button' %>
</div>
  <%# FIX_ME uncomment will_paginate %>
<div><br /><br /><%#= will_paginate @newsletters %></div>
<% end %>

app/views/newsletter/newsletters/new.html.erb
<%= title "New Newsletter" %>

<%#= render :partial => 'form' %>
<%= render "form", newsletter: @newsletter %>

<%= content_for :page_navigation do %>
<div>
  <%= link_to "Back to List", newsletters_path, :class => 'button' %>
</div>
<% end %>

app/views/newsletter/newsletters/show.css.erb
<%= @newsletter.design.stylesheet_text %>

app/views/newsletter/newsletters/show.html.erb
<% unless is_email? %>
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title><%= @newsletter.name %></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<%= "/newsletters/#{@newsletter.id}/stylesheet.css" %>"/>
    <%= render 'newsletter/newsletters/head' %>
  </head>
  <body>
<% else %>
  <!DOCTYPE html>
  <style>
    <%= @newsletter.design.stylesheet_text %>
  </style>
<% end %>
  <%= render :inline => File.readlines(@newsletter.design.view_path).join, :locals => @newsletter.locals %>
<% unless is_email? %>
  </body>
  </html>
<% end %>