config/routes.rb
Newsletter::Engine.routes.draw do

  resources :newsletters, except: [:show,:index] do
    member do 
      get :unpublish
      get :publish
      get :editor
    end
    collection do
      get :sort
    end
    resources :pieces, :only => [:new]
  end
  resources :pieces, :only => [:edit,:create,:update,:destroy]
  resources :designs do
    resources :elements, :only => [:index,:new,:create]
  end
  resources :elements, :only => [:edit,:create,:update,:destroy]

  # get "/:newsletter_id/areas/:id/sort" => "areas#sort", to: 'sort_area'
  get '/:newsletter_id/areas/:id/sort', to: 'areas#sort', as: 'sort_area'

  get '/newsletters/:id/:mode' => 'newsletters#show', to: :public_newsletter_mode
  get '/newsletters/:id/public' => 'newsletters#show', to: :public_newsletter
  get '/newsletters/:id' => 'newsletters#show', to: :newsletter
  get '/newsletters' => 'newsletters#index', to: :newsletters
  root :to => 'newsletters#index'
end

#public top-level routes
Rails.application.routes.draw do
  get '/newsletters/archive' => 'newsletter/newsletters#archive', to: :newsletter_archive
  get '/newsletters/:id/:mode' => 'newsletter/newsletters#show', to: :public_newsletter_mode
  get '/newsletters/:id/public' => 'newsletter/newsletters#show', to: :public_newsletter
end

app/models/newsletter/application_record.rb
module Newsletter
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
    table_name_prefix= "newsletter_"
  end
end

app/models/newsletter/design.rb
=begin rdoc
Author::    Chris Hauboldt (mailto:biz@lnstar.com)
Copyright:: 2009 Lone Star Internet Inc.

Newsletter::Designs define a main layout, with areas to group Elements/Pieces.


=end
# FIX_ME uncomment deleteable
# This was commented out when this error was caused at http://localhost:3000/newsletter/designs/3/elements
# ArgumentError (Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)):

# (eval):1:in `initialize'
# Started GET "/newsletter/designs/3/elements" for ::1 at 2022-07-05 12:34:44 -0700
# Processing by Newsletter::ElementsController#index as HTML
#   Parameters: {"design_id"=>"3"}
#   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
# Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.5ms | Allocations: 7804)


# require "deleteable"

module Newsletter
  class Design < ApplicationRecord
    has_many :elements, -> { order("name") }, class_name: 'Newsletter::Element'
    has_many :areas, -> { order("name") }, :class_name => 'Newsletter::Area'

    has_many :newsletters, foreign_key: :newsletter_design_id
    belongs_to :updated_by, required: true, class_name: "User"
    #relationships above

    scope :active, -> { where("deleted_at is null") }
    # scopes above

    # validates :name, presence: true, uniqueness: true
    # validations above

    # attr_protected :id
    #FIXME: make this work with deletable or convert to auditable, and extend it to access destroyed records
    #validates_uniqueness_of :name

    # Export a design's data to a YAML file. 
    def export(filename=nil)
      filename = "#{Newsletter.settings.designs_path}/exports/#{name_as_path}-export.yaml" unless filename
      FileUtils.mkdir_p(File.dirname(filename))
      File.open(filename,'w') do |file|
        YAML.dump( {
          :name => name,
          :html_text => html_text,
          :stylesheet_text => stylesheet_text,
          :description => description,
          :areas => areas.collect{|area| area.export_fields}, 
          :elements => elements.collect{|element| element.export_fields},
          :images => base64_encoded_images
        },file)
      end
    end
  
    # Import a design from a YAML file, 
    # Parameters:
    #   filename - path/name of file on filesystem
    #   design_name => rename design if already taken
    def self.import(filename,design_name=nil,updater)      
      raise "You must give a filename to import!" unless filename
      data = YAML.load_file(filename)
      design = nil
      transaction do 
        data[:name] = design_name if design_name
        design = Design.create(:name => data[:name], 
          :html_text => data[:html_text],
          :description => data[:description],
          :stylesheet_text => data[:stylesheet_text],
          updated_by: updater)
        data[:areas].each do |area_data|
          Area.import(design,area_data, updater)
        end
        data[:elements].each do |element_data|
          Element.import(design,element_data, updater)
        end
        design.import_images(data[:images])
      end
      raise "Error importing design: #{design.errors.full_messages.join("\n  ")}" unless design.valid?
      design
    end

    # returns path to newsletter design for use in views and is the same for actual file
    def view_path(this_name=nil)
      this_name ||= name
      File.join(base_design_path(this_name),'layout.html.erb')
    end
  
    # returns the path to the base of the design's files
    def base_design_path(this_name=nil)
      this_name ||= name
      ndp = 
      File.join(::Newsletter::Design.designs_path,'designs',name_as_path(this_name))
    end

    # returns the image filenames inside a design
    def images
      Dir.glob(File.join(images_path,'*.*')).map{|f| File.basename(f)} || []
    rescue => e
      []
    end

    # returns the images as an array of base64 encoded strings
    def base64_encoded_images
      images.map {|image| {
        name: image,
        data: Base64.encode64(File.binread(File.join(images_path,image)))
      }}
    end

    # returns where a design's images should go, can override for 'old_name'
    def images_path(the_name=nil)
      the_name ||= name
      File.join('public','images',name_as_path(the_name)) 
    end

    # move a design's images on name change
    def move_images(old_name=nil, new_name=nil)
      old_name ||= @old_name
      name ||= new_name
      return unless old_name && old_name != name
      FileUtils.mv(images_path(old_name),images_path)
    end

    # imports images from array of base64 encoded images
    def import_images(image_imports)
      image_imports ||= []
      FileUtils.mkdir_p(images_path)
      image_imports.each do |image|
        File.binwrite(File.join(images_path,image[:name]),
          Base64.decode64(image[:data])
        )
      end
    end

    def html_text
      return @html_text if @html_text.present?
      @html_text = read_design
    end
  
    def html_text=(text)
       @html_text = text
    end
  
    def name=(new_name)
      return if self[:name].eql?(new_name)
      @old_name = self[:name] unless @old_name
      self[:name] = new_name
    end
  
    # def save(*args)
    #   transaction do 
    #     move_design_on_name_change
    #     write_design
    #     super
    #   end
    # end  
  
    # returns a version of name that is nice for filesytem use
    def name_as_path(this_name=nil)
      this_name = name unless this_name
      this_name.gsub(/[^a-zA-Z0-9-]/,'_')
    end
    # FIX_ME turn Deletable back on
    # include Deleteable

    def self.designs_path
      Rails.application.config_for(:newsletter).designs_path
    end
    
        
    protected
    def read_design
      File.readlines(view_path).join
    rescue => e
      #flash[:warning] << "Couldn't open design for element '#{name}' which should exist at: #{file_path} #{e.message}"
      ""
    end

    def write_all_designs
      areas.collect{|area| area.elements}.flatten.uniq.each{|element| element.send(:write_design)}
      write_design
    end
  
    def move_design_on_name_change
      return unless @old_name and File.exists?(view_path(@old_name))
      FileUtils.mv(base_design_path(@old_name),base_design_path)
      move_images(@old_name, name)
    end

    def write_design
      FileUtils.mkdir_p(File.dirname(view_path)) unless File.exists?(File.dirname(view_path))
      File.open(view_path,File::WRONLY|File::TRUNC|File::CREAT) do |file|
        file.write html_text
      end
    end

    # methods above
  end
end

app/controllers/newsletter/application_controller.rb
require 'cancancan'
module Newsletter
  class ApplicationController < ActionController::Base
    # layout Newsletter.layout
    # render layout: false

    load_and_authorize_resource

    helper :'newsletter/layout'
  end
end

app/controllers/newsletter/areas_controller.rb
module Newsletter 
  class AreasController < ApplicationController
    
    before_action :find_area, :except => [:create, :new, :index]
    before_action :find_design, :except => [:destroy,:sort]
  
    def sort
      @newsletter = Newsletter.find(params[:newsletter_id])
      @area.pieces.active.by_newsletter(@newsletter).each do | piece |
        piece.update_attribute(:sequence, params["piece"].index(piece.id.to_s).to_i+1)
      end
      head :ok
    end
  
    protected
  
    def find_design
      @design = Design.find(params[:design_id])
    end
    
    def find_area
      @area = Area.find(params[:id])
    end
  end
end

app/controllers/newsletter/designs_controller.rb
# FIX_ME uncomment deleteable
require "deleteable"

module Newsletter
  class DesignsController < ApplicationController
    before_action :find_design, :except => [:new, :create, :index]

    # FIX_ME uncomment deleteable
    # include DeleteableActions

    def index
      @designs = Design.order(:name).paginate(page: (params[:page] || 1), 
        per_page: (params[:per_page] || 30))
    end

    def show
      @areas = @design.areas.active
    end

    def new
      @design = Design.new
    end

    def edit
    end

    # POST /designs
    def create
      @design = Design.new(design_params)
      @design.updated_by = current_user

      if @design.save
        redirect_to edit_design_path(@design), notice: "Design was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /designs/1
    def update
      if @design.update(design_params)
        redirect_to edit_design_path(@design), notice: "Design was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @design.delete
      redirect_to(designs_url)
    end
    
    protected
    
    def find_design
      @design = Design.find(params[:id])
    end

    def design_params
      params.require(:design).permit(:name,:description, :stylesheet_text, :html_text, newsletters_attributes: [:design_id, :name, :description])
    end

  end
end

app/controllers/newsletter/elements_controller.rb
module Newsletter
  class ElementsController < ::Newsletter::ApplicationController
    before_action :authenticate_user!
    before_action :find_element, :except => [:new,:create,:index]
    before_action :find_design
    before_action :find_fields, :except => [:new,:create,:index]
    before_action :find_field_types, :only => [:new,:create,:edit,:update]
    
    # include DeleteableActions  

    def index
      @elements = @design.elements#.by_design(@design).paginate(:page => params[:page])
    end

    def new
      @element = @design.elements.build
      @fields = [Field.new]
    end

    def edit
    end

    def create
      @element            = @design.elements.build(element_params)
      @element.updated_by = current_user

      respond_to do |format|
        if @element.save  
          format.html { redirect_to design_elements_path(@design), notice: 'Design element was successfully created.' }
          # format.json { render :show, status: :created, location: @element }
        else
          format.html { render :new, status: :unprocessable_entity }
          # format.json { render json: @element.errors, status: :unprocessable_entity }
        end
      end      
    end
    
    def update
      respond_to do |format|
        if @element.update_attributes(params[:element])
          flash[:notice] = 'Element was successfully updated.'
          format.html { redirect_to(design_elements_path(@design)) }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @element.errors, :status => :unprocessable_entity }
        end
      end
    end

    def destroy
      @element.destroy
      redirect_to(design_elements_path(@design))
    end
  
    protected
    def find_element
      @element ||= Element.find_by(id: params[:id])
    end
  
    def find_design
      return @design ||= @element.design if @element && @element.design.present?
      @design ||= Design.find_by(id: params[:design_id])
    end
  
    def find_fields
      return @fields ||= @element.fields if @element && @element.fields.present?
      @fields ||= [Field.new]
    end
  
    def find_field_types
      @field_types ||= Field.valid_types
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name, :description, :html_design, :deleted_at, :design_id)
    end

  end
end

app/controllers/newsletter/fields_controller.rb
module Newsletter
  class FieldsController < ApplicationController
  end
end

app/controllers/newsletter/newsletters_controller.rb
module Newsletter
  class NewslettersController < ApplicationController
    # before_action :_set_current_user
    # FIX_ME: before_action :authenticate! should be here instead
    before_action :authenticate_user!
    before_action :set_newsletter, only: %i[ show edit update destroy ]

    helper_method :newsletter
    def sort
      Newsletter.all.each do | newsletter |
        newsletter.sequence = params["newsletters"].index(newsletter.id.to_s)+1
        newsletter.save
      end
      head :ok
    end
  
    def archive
      @newsletters = Newsletter.published
      render :layout => ::Newsletter.archive_layout
    end

    def stylesheet

    end
  
    def publish
      if @newsletter.publish
        flash[:notice] = 'Newsletter Published'
      else
        flash[:notice] = @newsletter.errors
      end
      redirect_to(newsletters_path)
    end
  
    def unpublish
      if @newsletter.unpublish
        flash[:notice] = 'Newsletter UnPublished'
      else
        flash[:notice] = @newsletter.errors
      end 
      redirect_to(newsletters_path)
    end
  
    def index
      @newsletters = ::Newsletter::Newsletter.active#.order('created_at desc, published_at desc').paginate(:page => params[:page])
    end
  
    def show
      return redirect_to(main_app.newsletter_archive_path) unless @newsletter.present?
      respond_to do |format|
        format.html { render layout: false }
        format.css  { render layout: false, content_type: 'text/css' }
      end
    end

    def editor
      params[:editor] = '1'
      render :show, layout: false
    end

    def new
      @newsleter  = Newsletter.new
      @designs    = Design.active
    end

    def edit
      @designs = Design.active
    end

    def create
      @newsletter = Newsletter.new(newsletter_params)
      best_user =User.last
      @newsletter.updated_by    = best_user

      if @newsletter.save
        redirect_to @newsletter, notice: "Newsletter was successfully created."
      else
        render :new, status: :unprocessable_entity
      end

    end

    def update
      if @newsletter.update_attributes(params[:newsletter])
        flash[:notice] = 'Newsletter was successfully updated.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        @designs = Design.active
        render :action => "edit"
      end
    end

    def destroy
      @newsletter.destroy
      redirect_to(newsletters_url)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_newsletter
        @newsletter = Newsletter.find(params[:id])
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      # strong_params = params.require(:newsletter).permit(:name, :description)
      # strong_params
      params.require(:newsletter).permit(:name, :description, :design_id)
    end
    
  end
end

app/controllers/newsletter/pieces_controller.rb
module Newsletter
  class PiecesController < ApplicationController
    before_action :find_newsletter
    before_action :find_element
    before_action :find_area

    def new
      @piece = Piece.new({
        :area_id => @area.id,
        :element_id => @element.id,
        :newsletter_id => @newsletter.id
      })
    end

    def edit
    end

    def create
      @piece = Piece.new(params[:piece])
      if @piece.save
        flash[:notice] = 'Piece was successfully created.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        render :action => "new"
      end
    end

    def update
      if @piece.update_attributes(params[:piece])
        flash[:notice] = 'Piece was successfully updated.'
        redirect_to(edit_newsletter_path(@newsletter))
      else
        render :action => "edit"
      end
    end

    def destroy
      @piece.destroy
      redirect_to(edit_newsletter_path(@newsletter))
    end
  
    protected 
  
    def find_newsletter
      @newsletter ||= (@piece.try(:newsletter) || 
        ::Newsletter::Newsletter.find(params[:newsletter_id] || 
        params[:piece][:newsletter_id]))
    end
  
    def find_element
      @element ||= (@piece.try(:element) || 
        Element.find(params[:element_id] || params[:piece][:element_id]))
    end
  
    def find_area
      @area ||= (@piece.try(:area) || 
        Area.find(params[:area_id] || params[:piece][:area_id]))
    end
  end
end

app/views/newsletter/elements/_field_fields.html.erb
<%= div_for f.object do %>
	<%= f.error_messages %>

	<%= f.label :name %>
	<%= f.text_field :name%><br />
	<%= f.label :label %>
	<%= f.text_field :label %><br />
	<%= f.label :description %>
	<%= f.text_field :description %><br />
	<%= f.label :type %>
	<%= f.select :type, options_for_select(@field_types.collect{|type| [type.gsub(/Newsletter::Field::/,'').humanize,type]}, f.object.class.name) %>
	<%= f.hidden_field :sequence, {class: 'sequence'} %>
	<%= f.link_to_remove "Remove", {class: 'button', style: 'margin-left: 130px;'} %>
    <hr>
<% end %>

app/views/newsletter/elements/_form.html.erb
<%# FIX_ME nested_form_for is before rails 4 %>
<%= form_with(model: element, url: [@design, element]) do |f| %>
  <% if element.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :description %>
  <%= f.text_field :description %><br />

  <% unless element.name.blank? %>
    <label>Element Filename</label>
        <div style="padding-top: 7px";><%= element.file_path.gsub(/^#{Newsletter.settings.designs_path}/,'') %></div>
        <br />
  <% end %>

  <%= f.label :html_text %>
  <%= f.text_area :html_text %><br />

  <div class='newsletter_parts_group' 
      style='margin-top: 10px; padding: 0 5px 5px 15px; border: thin dashed black; background-color: #eee'>
      
      <h2 style='font-size: 10pt; '>Fields</h2>
      The HTML code field above should contain (at the least):
      
      <ul>
        <li>&lt;%= [field_name] %&gt; for each Text field.</li>
        <li>&lt;%= filter([field_name]) %&gt; for each Textarea.</li>
        <li>&lt;%= image_tag([field_name]) %&gt; for each Inlineasset that will contain an image.</li>
        <li>&lt;%= link_to([field_name]) %&gt; for each Inlineasset that will contain a link.</li>
      </ul>

      <%= content_for :head do %>
        <script>
        </script>
      <% end %>
  </div>

  <div class='newsletter_parts_group' 
    style='margin-top: 10px; padding: 0 5px 5px 15px; border: thin dashed black; background-color: #eee'>

    <h2 style='padding-bottom: 0; margin-bottom: 0; font-size: 10pt; '>Areas</h2>
    <% @design.areas.each do |area| %>
      <%= check_box_tag "element[area_ids][#{area.id}]", 
        area.id, 
        element.areas.include?(area), 
        name: "element[area_ids][]" %>
      <%= label_tag "element[area_ids][#{area.id}]", area.name %><br/>
    <% end %>
  </div>

  <div class="submit_button"><%= f.submit "Submit", :class => 'button' %></div>

<% end %>

app/views/newsletter/elements/edit.html.erb
<%= title "Edit Element '#{@element.name}'" %>

<%= render "form", element: @element %>


<%= content_for :page_navigation do %>
  <div>
    <%= link_to "View All", design_elements_path(@design), :class => 'button' %>
  </div>
<% end %>

app/views/newsletter/elements/index.html.erb
<%= title "Elements" %>

<table class="list" cellpadding="1" cellspacing="0">
  <tr class="title">
    <td>Name</td>
    <td>Description</td>
    <td colspan="2"> </td>    
  </tr>
  <% for element in @elements %>
    <tr class="<%= cycle('odd','even') %>" id="element_<%= element.id %>">
      <td><%=h element.name %></td>
      <td><%=h element.description %></td>
      <td><%= link_to "Edit", edit_element_path(element), :class => 'button' %></td>
      <td><%= link_to "Delete", element, :confirm => 'Are you sure?', :method => :delete, :class => 'button' %></td>
    </tr>
  <% end %>
</table>


<%= content_for :page_navigation do %>
<div>
  <%= link_to "Back to Design", edit_design_path(@design), :class => 'button' %>
  <%= link_to "New Newsletter Element", new_design_element_path(@design), :class => 'button' %>
</div>
<% end %>

app/views/newsletter/elements/new.html.erb
<%#  %>
<%= title "New Element" %>

<%= render "form", element: @element %>

<br>

<%= content_for :page_navigation do %>
  <div>
    <%= link_to "Back to List", design_elements_path(@design), :class => 'button' %>
  </div>
<% end %>

app/views/newsletter/elements/show.html.erb
<%= title "Element" %>

<p>
  <strong>Name:</strong>
  <%=h @element.name %>
</p>
<p>
  <strong>Description:</strong>
  <%=h @element.description %>
</p>
<p>
  <strong>Html Design Text:</strong>
  <%=h @element.html_text %>
</p>

<%= content_for :page_navigation do %>
<div>
  <%= link_to "Edit", edit_element_path(@element), :class => 'button' %> 
  <%= link_to "Delete", @element, :confirm => 'Are you sure?', :method => :delete, :class => 'button' %> 
  <%= link_to "View All", design_elements_path(@design), :class => 'button' %>
</div>
<% end %>